text meessage

message Info:  {
  CONSTRUCTOR_ID: 508332649,
  SUBCLASS_OF_ID: 2030045667,
  className: 'Message',
  classType: 'constructor',
  out: true,
  mentioned: false,
  mediaUnread: false,
  silent: false,
  post: true,
  fromScheduled: false,
  legacy: false,
  editHide: false,
  ttlPeriod: null,
  id: 22,
  fromId: null,
  peerId: {
    CONSTRUCTOR_ID: 2728736542,
    SUBCLASS_OF_ID: 47470215,
    className: 'PeerChannel',
    classType: 'constructor',
    channelId: Integer { value: 2191249324n }
  },
  replyTo: null,
  date: 1723443574,
  message: 'Hi',
  media: null,
  replyMarkup: null,
  entities: null,
  views: 1,
  forwards: 0,
  replies: null,
  editDate: null,
  pinned: false,
  postAuthor: null,
  groupedId: null,
  restrictionReason: null,
  action: undefined,
  noforwards: false,
  reactions: null,
  flags: 17410,
  invertMedia: false,
  fromBoostsApplied: null,
  savedPeerId: null
}